export const Collections = [
  {
    image: "https://via.placeholder.com/150/9D5BCD/FFFFFF?text=NFT+1",
    name: "Collection Example",
    floor: "0.99 ETH",
    average: "1.16 ETH",
    ceiling: "1.19 ETH",
    volume: "$9,316",
    change: "4%",
  },
  {
    image: "https://via.placeholder.com/150/FF3D77/FFFFFF?text=NFT+2",
    name: "Collection Example",
    floor: "0.99 ETH",
    average: "1.16 ETH",
    ceiling: "1.19 ETH",
    volume: "$9,316",
    change: "4%",
  },
  {
    image: "https://via.placeholder.com/150/8000CE/FFFFFF?text=NFT+3",
    name: "Collection Example",
    floor: "0.99 ETH",
    average: "1.16 ETH",
    ceiling: "1.19 ETH",
    volume: "$9,316",
    change: "4%",
  },
  {
    image: "https://via.placeholder.com/150/9F56D1/FFFFFF?text=NFT+4",
    name: "Collection Example",
    floor: "0.99 ETH",
    average: "1.16 ETH",
    ceiling: "1.19 ETH",
    volume: "$9,316",
    change: "4%",
  },
  {
    image: "https://via.placeholder.com/150/FF3D77/FFFFFF?text=NFT+5",
    name: "Collection Example",
    floor: "0.99 ETH",
    average: "1.16 ETH",
    ceiling: "1.19 ETH",
    volume: "$9,316",
    change: "4%",
  },
  {
    image: "https://via.placeholder.com/150/8000CE/FFFFFF?text=NFT+6",
    name: "Collection Example",
    floor: "0.99 ETH",
    average: "1.16 ETH",
    ceiling: "1.19 ETH",
    volume: "$9,316",
    change: "4%",
  },
];
